site_name: Jacob Redis Book
site_description: "Jacob's Redis 技术与实战教程"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"
  - 'Redis 介绍':
    - '第一节 Redis 不得不去掌握的关键' : 'chap1/1redis_intro.md'
  - 'Redis 基础篇':
    - '第一节 基本架构： 键值数据库' : 'chap2/1redis_kv.md'
    - '第二节 数据结构：Redis为什么那么快？' : 'chap2/2redis_slowquery.md'
    - '第三节 高性能IO模型：Redis为什么那么快？' : 'chap2/3redis_io.md'
    - '第四节 Redis宕机，如何避免数据丢失：AOF日志' : 'chap2/4redis_aof_log.md'
    - '第五节 Redis宕机，Redis如何实现快速恢复RDB' : 'chap2/5redis_rdb_snapshot.md'
    - '第六节 数据同步：主从库数据一致' : 'chap2/6redis_master_slave_replicate.md'
    - '第七节	哨兵机制：主库不间断服务' : 'chap2/7redis_master_rescue.md'
    - '第八节	哨兵集群：哨兵挂了，主从库切换' : 'chap2/8redis_sentinel.md'
    - '第九节 切片集群：数据增多了，是该加内存还是加实例' : 'chap2/9redis_slot.md'
    - 'Redis核心技术基础总结篇' : 'chap2/10redis_basic_sum.md'
  - 'Redis 数据结构':
    - '第一节 Redis的String类型数据结构' : 'chap3/1redis_string.md'
    - '第二节 Redis有那些数据结构适合做统计' : 'chap3/2redis_sets.md'
    - '第三节 GEO，一种可以实现LBS服务的数据结构' : 'chap3/3redis_geo.md'
    - '第四节 根据时间序列数据的特点，选择合适的存储方案' : 'chap3/4redis_timeseries.md'
    - '第五节 如何使用redis实现消息队列的需求' : 'chap3/5redis_stream.md'
    - '第六节 Redis 的数据结构' : 'chap3/6redis_ds_sum.md'


repo_url: https://github.com/Chao-Xi/jxredisbook.git
repo_name: "jxredisbook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'pink'
    accent: 'pink'
  i18n:
    prev: 'Previous'
    next: 'Next'
